name: React CI

on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v2
          - name: Setup Yarn
            uses: borales/actions-yarn@v2.0.0
          - name: Install Dependencies
            run: cd src/frontend && yarn install
          - name: Build
            run: cd src/frontend && CI='' yarn build
          - name: Run Unit Tests
            run: cd src/frontend && yarn test --watchAll=false
